apiVersion: v1
kind: Service
metadata:
name: demo-app
namespace: demo
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
type: LoadBalancer
selector:
app: demo-app
ports:
- port: 80
targetPort: 3000
protocol: TCP